import Navigation from "@/app/components/Navigation"
import Logo from "./components/Logo"

// you can add more metadata here, and customize the title of each page also.
export const metadata = {
  title: 'The Wild Oasis!',
  description: 'Generated by Next.js',
}


// NOTE: root layout is required
export default function RootLayout({ children }) {
  return (
    // NOTE: in root layout both html and body tags are required
    <html lang="en">
      <body>
        <header>
          <Logo />
          <Navigation />
        </header>
        <main>
          {children}
        </main>
        <footer>Copyright &copy; by The Wild Oasis</footer>
      </body>
    </html>
  )
}
