import Logo from "@/app/_components/Logo"
import Navigation from "@/app/_components/Navigation"

import "@/app/_styles/globals.css"
// you can add more metadata here, and customize the title of each page also.
export const metadata = {
  title: 'The Wild Oasis!',
  description: 'Generated by Next.js',
}


// NOTE: root layout is required
export default function RootLayout({ children }) {
  return (
    // NOTE: in root layout both html and body tags are required
    <html lang="en">
      <body>
        <header className="bg-primary-950 text-primary-100 min-h-screen">
          <Logo />
          <Navigation />
        </header>
        <main>
          {children}
        </main>
        <footer>Copyright &copy; by The Wild Oasis</footer>
      </body>
    </html>
  )
}
